#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2020, Oracle and/or its affiliates.  All Rights Reserved.
#
# FS QA Test No.515
#
# simple parent pointer test
#

seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
seqfull="$seqres.full"
status=1	# failure is the default!
trap "cleanup; exit \$status" 0 1 2 3 15

cleanup()
{
	cd /
	rm -f $tmp.*
}

filter_dbval()
{
	awk '{ print $4 }'
}

full()
{
    echo ""            >>$seqfull
    echo "*** $* ***"  >>$seqfull
    echo ""            >>$seqfull
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/reflink
. ./common/inject
. ./common/parent

# remove previous $seqres.full before test
rm -f $seqres.full

# Modify as appropriate
_supported_os Linux
_supported_fs xfs
_require_scratch
_require_xfs_io_error_injection "delayed_attr"

# real QA test starts here

# Create a directory tree using a protofile and
# make sure all inodes created have parent pointers

protofile=$tmp.proto

cat >$protofile <<EOF
DUMMY1
0 0
: root directory
d--777 3 1
: a directory
testfolder1 d--755 3 1
file1 ---755 3 1 /dev/null
$
: back in the root
testfolder2 d--755 3 1
file2 ---755 3 1 /dev/null
: done
$
EOF

if [ $? -ne 0 ]
then
    _fail "failed to create test protofile"
fi

echo "*** create FS"

rm -f $seqfull
_scratch_unmount >/dev/null 2>&1

_scratch_mkfs_xfs -f -n parent=1 -n delattr -p $protofile >>$seqfull 2>&1 \
	|| _fail "mkfs failed"
echo "*** check FS"
_check_scratch_fs

echo "*** mount FS"
full " mount"
_scratch_mount >>$seqfull 2>&1 \
	|| _fail "mount failed"

testfolder1="testfolder1"
testfolder2="testfolder2"
file1="file1"
file2="file2"
file3="file3"
file4="file4"
file5="file5"
file1_ln="file1_link"

echo ""
echo "Create parent pointer test"
_verify_parent "$testfolder1" "$file1" "$testfolder1/$file1"

echo ""
echo "Move parent pointer test"
mv $SCRATCH_MNT/$testfolder1/$file1 $SCRATCH_MNT/$testfolder2/$file1
_verify_parent "$testfolder2" "$file1" "$testfolder2/$file1"

echo ""
echo "Hard link parent pointer test"
ln $SCRATCH_MNT/$testfolder2/$file1 $SCRATCH_MNT/$testfolder1/$file1_ln
_verify_parent "$testfolder1" "$file1_ln"  "$testfolder1/$file1_ln"
_verify_parent "$testfolder1" "$file1_ln"  "$testfolder2/$file1"
_verify_parent "$testfolder2" "$file1"     "$testfolder1/$file1_ln"
_verify_parent "$testfolder2" "$file1"     "$testfolder2/$file1"

echo ""
echo "Remove hard link parent pointer test"
ino="$(stat -c '%i' $SCRATCH_MNT/$testfolder2/$file1)"
rm $SCRATCH_MNT/$testfolder2/$file1
_verify_parent    "$testfolder1" "$file1_ln" "$testfolder1/$file1_ln"
_verify_no_parent "$file1" "$ino" "$testfolder1/$file1_ln"

echo ""
echo "Rename parent pointer test"
ino="$(stat -c '%i' $SCRATCH_MNT/$testfolder1/$file1_ln)"
mv $SCRATCH_MNT/$testfolder1/$file1_ln $SCRATCH_MNT/$testfolder1/$file2
_verify_parent    "$testfolder1" "$file2"    "$testfolder1/$file2"
_verify_no_parent "$file1_ln" "$ino" "$testfolder1/$file2"

echo ""
echo "Over write parent pointer test"
touch $SCRATCH_MNT/$testfolder2/$file3
_verify_parent    "$testfolder2" "$file3"    "$testfolder2/$file3"
ino="$(stat -c '%i' $SCRATCH_MNT/$testfolder2/$file3)"
mv -f $SCRATCH_MNT/$testfolder2/$file3 $SCRATCH_MNT/$testfolder1/$file2
_verify_parent    "$testfolder1" "$file2"    "$testfolder1/$file2"

echo "*** unmount FS"
full "umount"
_scratch_unmount >>$seqfull 2>&1 \
        || _fail "umount failed"

echo "*** done"
rm $seqfull
status=0

# success, all done
status=0
exit
